export const BUS_ROUTES_CONSTANTS = [
  {
    routeNumber: '1',
    routeName: 'Marietta Blvd/Joseph E Lowery Blvd',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '2',
    routeName: 'Ponce de Leon Avenue / Druid Hills',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '3',
    routeName: 'Martin Luther King Jr Dr/Auburn Ave',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '4',
    routeName: 'Moreland Avenue',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '5',
    routeName: 'Piedmont Road / Sandy Springs',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '6',
    routeName: 'Clifton Road / Emory',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '8',
    routeName: 'North Druid Hills Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '9',
    routeName: 'Boulevard / Tilson Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '12',
    routeName: 'Howell Mill Road / Cumberland',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '14',
    routeName: '14th Street / Blandtown',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '15',
    routeName: 'Candler Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '19',
    routeName: 'Clairmont Road / Howard Avenue',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '21',
    routeName: 'Memorial Drive',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '24',
    routeName: 'McAfee / Hosea Williams',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '25',
    routeName: 'Peachtree Boulevard',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '26',
    routeName: 'Marietta Street / Perry Boulevard',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '27',
    routeName: 'Cheshire Bridge Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '30',
    routeName: 'LaVista Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '32',
    routeName: 'Bouldercrest',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '34',
    routeName: 'Gresham Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '36',
    routeName: 'N Decatur Road / Virginia Highland',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '37',
    routeName: 'Defoors Ferry Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '39',
    routeName: 'Buford Highway',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '40',
    routeName: 'Peachtree Street / Downtown',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '42',
    routeName: 'Pryor Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '47',
    routeName: 'I-85 Access Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '49',
    routeName: 'McDonough Boulevard',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '50',
    routeName: 'Donald Lee Hollowell Parkway',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '51',
    routeName: 'Joseph E Boone Boulevard',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '55',
    routeName: 'Jonesboro Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '58',
    routeName: 'Hollywood Road / Lucile Avenue',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '60',
    routeName: 'Hightower Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '66',
    routeName: 'Lynhurst Drive / Princeton Lakes',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '68',
    routeName: 'Benjamin E Mays Drive',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '71',
    routeName: 'Cascade Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '73',
    routeName: 'Fulton Industrial',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '74',
    routeName: 'Flat Shoals Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '75',
    routeName: 'Lawrenceville Highway',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '78',
    routeName: 'Cleveland Avenue',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '79',
    routeName: 'Sylvan Hills',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '81',
    routeName: 'Venetian Hills / Delowe Drive',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '82',
    routeName: 'Camp Creek / South Fulton Parkway',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '83',
    routeName: 'Campbellton Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '84',
    routeName: 'Washington Rd/Camp Crk Marketplace',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '85',
    routeName: 'Roswell',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '86',
    routeName: 'Fairington Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '87',
    routeName: 'Roswell Road / Sandy Springs',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '89',
    routeName: 'Old National Highway',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '93',
    routeName: 'Headland Drive / Main Street',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '94',
    routeName: 'Northside Drive',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '95',
    routeName: 'Metropolitan Parkway',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '102',
    routeName: 'North Avenue / Little Five Points',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '103',
    routeName: 'Peeler Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '104',
    routeName: 'Winters Chapel Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '107',
    routeName: 'Glenwood',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '110',
    routeName: 'Peachtree Road / Buckhead',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '111',
    routeName: 'Snapfinger Woods',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '114',
    routeName: 'Columbia Drive',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '115',
    routeName: 'Covington Highway',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '116',
    routeName: 'Redan Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '117',
    routeName: 'Rockbridge Road / Panola Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '119',
    routeName: 'Hairston Road / Stone Mtn Village',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '120',
    routeName: 'East Ponce De Leon Avenue',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '121',
    routeName: 'Memorial Drive / N Hairston Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '123',
    routeName: 'Church Street',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '124',
    routeName: 'Pleasantdale Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '125',
    routeName: 'Clarkston',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '126',
    routeName: 'Embry Hills',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '132',
    routeName: 'Tilly Mill Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '133',
    routeName: 'Shallowford Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '140',
    routeName: 'North Point Parkway',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '141',
    routeName: 'Haynes Bridge Road / Milton',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '142',
    routeName: 'East Holcomb Bridge Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '143',
    routeName: 'Windward Park & Ride',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '148',
    routeName: 'Mount Vernon Highway',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '150',
    routeName: 'Dunwoody Village',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '153',
    routeName: 'James Jackson Parkway',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '155',
    routeName: 'Pittsburgh',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '162',
    routeName: 'Myrtle Drive / Alison Court',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '165',
    routeName: 'Fairburn Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '172',
    routeName: 'Sylvan Road / Virginia Avenue',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '178',
    routeName: 'Empire Blvd / Southside Ind Park',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '180',
    routeName: 'Roosevelt Highway',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '181',
    routeName: 'Washington Road / Fairburn',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '183',
    routeName: 'Greenbriar',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '185',
    routeName: 'Alpharetta',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '186',
    routeName: 'Rainbow Drive / South DeKalb',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '188',
    routeName: 'Oakley Industrial',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '189',
    routeName: 'Flat Shoals Road / Scofield Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '191',
    routeName: 'Riverdale / ATL Intl Terminal',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '192',
    routeName: 'Old Dixie / Tara Boulevard',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '193',
    routeName: 'Morrow / Jonesboro',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '194',
    routeName: 'Conley Road / Mt Zion',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '195',
    routeName: 'Forest Parkway',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '196',
    routeName: 'Upper Riverdale',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '197',
    routeName: 'Battle Creek Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '198',
    routeName: 'Southlake Parkway',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '201',
    routeName: 'Six Flags Over Georgia',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '221',
    routeName: 'Memorial Drive Limited',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '295',
    routeName: 'Metropolitan Campus Express',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '800',
    routeName: 'Lovejoy',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '809',
    routeName: 'Monroe Drive / Boulevard',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '813',
    routeName: 'Atlanta University Center',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '816',
    routeName: 'North Highland Avenue',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '823',
    routeName: 'Belvedere',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '825',
    routeName: 'Johnson Ferry Road',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '832',
    routeName: 'Grant Park',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '850',
    routeName: 'Carroll Heights / Fairburn Heights',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '853',
    routeName: 'Center Hill',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '856',
    routeName: 'Baker Hills / Wilson Mill Meadows',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '865',
    routeName: 'Boulder Park Drive',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '867',
    routeName: 'Peyton Forest / Dixie Hills',
    anchoredStations: [],
    legs: [],
  },
  {
    routeNumber: '899',
    routeName: 'Old Fourth Ward',
    anchoredStations: [],
    legs: [],
  },
];
