import { StationGeolocation } from '../models/api.interfaces';

export const STATIONS_INFO_CONSTANTS: StationGeolocation[] = [
  {
    id: 'DORAVILLE STATION',
    name: 'Doraville',
    latitude: 33.902079,
    longitude: -84.280389,
  },
  {
    id: 'CHAMBLEE STATION',
    name: 'Chamblee',
    latitude: 33.886944,
    longitude: -84.307222,
  },
  {
    id: 'BROOKHAVEN STATION',
    name: 'Brookhaven',
    latitude: 33.860705,
    longitude: -84.340003,
  },
  {
    id: 'LENOX STATION',
    name: 'Lenox',
    latitude: 33.847144,
    longitude: -84.35631,
  },
  {
    id: 'LINDBERGH CENTER STATION',
    name: 'Lindbergh Center',
    latitude: 33.821995,
    longitude: -84.367447,
  },
  {
    id: 'ARTS CENTER STATION',
    name: 'Arts Center',
    latitude: 33.789705,
    longitude: -84.387789,
  },
  {
    id: 'MIDTOWN STATION',
    name: 'Midtown',
    latitude: 33.781121,
    longitude: -84.386345,
  },
  {
    id: 'NORTH AVE STATION',
    name: 'North Avenue',
    latitude: 33.771712,
    longitude: -84.386699,
  },
  {
    id: 'CIVIC CENTER STATION',
    name: 'Civic Center',
    latitude: 33.766305,
    longitude: -84.387209,
  },
  {
    id: 'PEACHTREE CENTER STATION',
    name: 'Peachtree Center',
    latitude: 33.75967,
    longitude: -84.387548,
  },
  {
    id: 'FIVE POINTS STATION',
    name: 'Five Points',
    latitude: 33.753826,
    longitude: -84.391571,
  },
  {
    id: 'GARNETT STATION',
    name: 'Garnett',
    latitude: 33.747845,
    longitude: -84.396415,
  },
  {
    id: 'WEST END STATION',
    name: 'West End',
    latitude: 33.73581,
    longitude: -84.41296,
  },
  {
    id: 'OAKLAND CITY STATION',
    name: 'Oakland City',
    latitude: 33.716848,
    longitude: -84.4252,
  },
  {
    id: 'LAKEWOOD FORT MCPHERSON STATION',
    name: 'Lakewood Fort McPherson',
    latitude: 33.700457,
    longitude: -84.428859,
  },
  {
    id: 'EAST POINT STATION',
    name: 'East Point',
    latitude: 33.677814,
    longitude: -84.440344,
  },
  {
    id: 'COLLEGE PARK STATION',
    name: 'Brookhaven',
    latitude: 33.651673,
    longitude: -84.448793,
  },
  {
    id: 'AIRPORT STATION',
    name: 'Airport',
    latitude: 33.640758,
    longitude: -84.446341,
  },
  {
    id: 'GEOGIA STATE STATION',
    name: 'Georgia State',
    latitude: 33.750539,
    longitude: -84.386464,
  },
  {
    id: 'KING MEMORIAL STATION',
    name: 'King Memorial',
    latitude: 33.749959,
    longitude: -84.37544,
  },
  {
    id: 'INMAN PARK STATION',
    name: 'Inman Park',
    latitude: 33.757497,
    longitude: -84.352797,
  },
  {
    id: 'EDGWEOOD CANDLER PARK STATION',
    name: 'Edgewood Candler Park',
    latitude: 33.762001,
    longitude: -84.339579,
  },
  {
    id: 'EAST LAKE STATION',
    name: 'East Lake',
    latitude: 0,
    longitude: 0,
  },
  {
    id: 'DECATUR STATION',
    name: 'Decatur',
    latitude: 0,
    longitude: 0,
  },
  {
    id: 'AVONDALE STATION',
    name: 'Avondale',
    latitude: 0,
    longitude: 0,
  },
  {
    id: 'KENSINGTON STATION',
    name: 'Kensington',
    latitude: 0,
    longitude: 0,
  },
  {
    id: 'INDIAN CREEK STATION',
    name: 'Indian Creek',
    latitude: 0,
    longitude: 0,
  },
  {
    id: 'GWCC/CNN CENTER STATION',
    name: 'GWCC/CNN Center',
    latitude: 0,
    longitude: 0,
  },
  {
    id: 'VINE CITY STATION',
    name: 'Vine City',
    latitude: 0,
    longitude: 0,
  },
  {
    id: 'ASHBY STATION',
    name: 'Ashby',
    latitude: 0,
    longitude: 0,
  },
  {
    id: 'WEST LAKE STATION',
    name: 'West Lake',
    latitude: 0,
    longitude: 0,
  },
  {
    id: 'HAMILTON E HOLMES STATION',
    name: 'Hamilton E Holmes',
    latitude: 0,
    longitude: 0,
  },
  {
    id: 'BANKHEAD STATION',
    name: 'Bankhead',
    latitude: 0,
    longitude: 0,
  },
];
